"""Local browser dashboard backed by the shared session state."""
from __future__ import annotations

from collections.abc import Callable
from threading import Thread
from typing import Any

from flask import Flask, jsonify, render_template_string, request
from werkzeug.serving import make_server

from .session import Session, format_duration
from .transports import VALID_COMMANDS

DEFAULT_WEB_BIND = "127.0.0.1"
DEFAULT_WEB_PORT = 8080


def serialize_state(session: Session, tcp_status: str = "NOT CONNECTED", udp_status: str = "DISABLED") -> dict[str, Any]:
    """Return a credential-free snapshot for terminal/web consumers."""
    with session.lock:
        stats, measurement = session.statistics, session.last_measurement
        return {
            "source": session.source,
            "replay": session.source == "REPLAY",
            "device": {
                "name": session.device,
                "mode": session.mode,
                "uptime_ms": session.uptime_ms,
                "uptime": format_duration((session.uptime_ms or 0) / 1000),
                "sequence": session.sequence,
                "sequence_gaps": stats.sequence_gaps,
            },
            "connection": {"tcp": tcp_status, "udp": udp_status},
            "session": {
                "samples": stats.samples,
                "normal_samples": stats.normal_samples,
                "test_samples": stats.test_samples,
                "duration_seconds": round(stats.duration_seconds(), 3),
                "duration": format_duration(stats.duration_seconds()),
            },
            "simulated_rf": {
                "label": "SOFTWARE-SIMULATED RF METRICS — not physical ESP32 measurements",
                "rssi_dbm": measurement.rssi_dbm if measurement else None,
                "noise_dbm": measurement.noise_dbm if measurement else None,
                "packet_success_percent": measurement.packet_success_percent if measurement else None,
            },
            "history": list(session.history),
        }


PAGE = r"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>embedded-rf dashboard</title>
<style>body{font:16px system-ui;margin:0;background:#10151c;color:#eaf1f8}main{max-width:1050px;margin:auto;padding:24px}.banner{padding:16px;border-radius:8px;background:#17344c}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin:16px 0}.card{background:#1b2430;padding:16px;border-radius:8px}.real{border-top:5px solid #40a9ff}.sim{border-top:5px solid #ffb020}.label{color:#9db0c3}.value{font-size:1.25rem}.warning{color:#ffd27a;font-weight:700}button{margin:4px;padding:8px 14px}canvas{width:100%;height:130px;background:#111821}#message{min-height:1.5em}</style></head>
<body><main><div class="banner"><h1>embedded-rf <span id="source">LIVE</span></h1><strong>REAL DEVICE/CONTROL TELEMETRY</strong> is shown separately from <span class="warning">SOFTWARE-SIMULATED RF METRICS</span>.</div>
<div class="grid"><section class="card real"><h2>REAL DEVICE/CONTROL TELEMETRY</h2><div id="device"></div></section><section class="card real"><h2>CONNECTION</h2><div id="connection"></div></section><section class="card"><h2>SESSION</h2><div id="session"></div></section></div>
<section class="card sim"><h2>SOFTWARE-SIMULATED RF METRICS</h2><p class="warning">Generated by Python or read from a replay CSV. These are NOT physical RF measurements from the ESP32.</p><div id="rf"></div><h3>SIMULATED RSSI</h3><canvas id="rssi"></canvas><h3>SIMULATED Noise</h3><canvas id="noise"></canvas><h3>SIMULATED Packet Success</h3><canvas id="success"></canvas></section>
<section class="card real"><h2>SAFE DEVICE CONTROL</h2><button onclick="command('STATUS')">STATUS</button><button onclick="command('ON')">ON</button><button onclick="command('OFF')">OFF</button><div id="message"></div></section>
<script>const val=(v,s='')=>v==null?'—':v+s;function rows(xs){return xs.map(([a,b])=>`<div><span class="label">${a}:</span> <span class="value">${b}</span></div>`).join('')}
function chart(id,data,key,color){const c=document.getElementById(id),d=devicePixelRatio||1,w=c.clientWidth*d,h=130*d;c.width=w;c.height=h;const x=c.getContext('2d');x.strokeStyle=color;x.lineWidth=2*d;x.beginPath();const vs=data.map(p=>p[key]);if(!vs.length)return;let lo=Math.min(...vs),hi=Math.max(...vs);if(lo===hi){lo--;hi++}vs.forEach((v,i)=>{const px=i*w/Math.max(1,vs.length-1),py=h-(v-lo)*h/(hi-lo);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
async function update(){try{const s=await fetch('/api/state',{cache:'no-store'}).then(r=>r.json());source.textContent=s.replay?'REPLAY MODE':'SOURCE: '+s.source;device.innerHTML=rows([['Device',s.device.name],['Mode',s.device.mode],['Uptime',s.device.uptime],['Telemetry sequence',val(s.device.sequence)],['Detected sequence gaps',s.device.sequence_gaps]]);connection.innerHTML=rows([['TCP status',s.connection.tcp],['UDP status',s.connection.udp]]);session.innerHTML=rows([['Total samples',s.session.samples],['NORMAL samples',s.session.normal_samples],['TEST samples',s.session.test_samples],['Duration',s.session.duration]]);rf.innerHTML=rows([['SIMULATED RSSI',val(s.simulated_rf.rssi_dbm,' dBm')],['SIMULATED noise',val(s.simulated_rf.noise_dbm,' dBm')],['SIMULATED packet success',val(s.simulated_rf.packet_success_percent,' %')]]);chart('rssi',s.history,'rssi','#55b8ff');chart('noise',s.history,'noise','#bd8cff');chart('success',s.history,'success','#64d98b')}catch(e){message.textContent='State unavailable: '+e}finally{setTimeout(update,750)}}
async function command(action){try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:action})}),j=await r.json();message.textContent=j.message||j.error}catch(e){message.textContent='Command failed: '+e}}update();</script></main></body></html>"""


def create_app(session: Session | None, status_provider: Callable[[], tuple[str, str]] | None = None,
               command_handler: Callable[[str], None] | None = None) -> Flask:
    app = Flask(__name__)

    @app.get("/")
    def index():
        return render_template_string(PAGE)

    @app.get("/api/state")
    def state():
        if session is None:
            return jsonify({"error": "Session state is unavailable"}), 503
        tcp, udp = status_provider() if status_provider else ("NOT CONNECTED", "DISABLED")
        return jsonify(serialize_state(session, tcp, udp))

    @app.post("/api/control")
    def control():
        payload = request.get_json(silent=True) or {}
        command = payload.get("command")
        if not isinstance(command, str) or command.strip().upper() not in VALID_COMMANDS:
            return jsonify({"error": "Command must be STATUS, ON, or OFF"}), 400
        normalized = command.strip().upper()
        if command_handler is None:
            return jsonify({"error": "Device control is unavailable for this source"}), 409
        try:
            command_handler(normalized)
        except (RuntimeError, ValueError) as error:
            return jsonify({"error": str(error)}), 503
        return jsonify({"ok": True, "message": f"Sent safe command: {normalized}"})

    return app


class WebDashboard:
    """Deterministically stoppable localhost WSGI server."""
    def __init__(self, app: Flask, bind: str = DEFAULT_WEB_BIND, port: int = DEFAULT_WEB_PORT):
        self.bind, self.port = bind, port
        self._server = make_server(bind, port, app, threaded=True)
        self.port = self._server.server_port
        self._thread = Thread(target=self._server.serve_forever, name="embedded-rf-web", daemon=False)

    @property
    def url(self) -> str:
        host = "127.0.0.1" if self.bind in {"0.0.0.0", "::"} else self.bind
        return f"http://{host}:{self.port}"

    def start(self) -> None:
        self._thread.start()

    def close(self) -> None:
        self._server.shutdown()
        self._thread.join(timeout=5)
        self._server.server_close()
